name: Draw ZMK keymap
on:
  push:
    paths:
      - 'config/*.keymap'
  workflow_dispatch:

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: caksoylar/keymap-drawer@main
        with:
          keymap_path: config/corne.keymap
          output_folder: keymap-drawer
          commit_message: "keymap-drawer: update svg [skip ci]"